---
title: "presentation_figures"
author: "Liyenne"
date: "2023-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
require(usethis) 
require(tidyverse)
require(tidylog)
#install.packages("remotes")
require(remotes)
#remotes::install_github("Between-the-Fjords/dataDownloader")
require(ggplot2)
require(dataDownloader)
require(vegan)
```

```{r initialize data}
get_file(node = "hk2cy",
         file = "PFTC_SA_clean_community_2023.csv",
         path = "../1_input", 
         remote_path = "community_data") 

com_data_full <- read_csv("../1_input/PFTC_SA_clean_community_2023.csv") #%>% 
  #distinct() %>% 
  #group_by(site_id, aspect, plot_id, species) %>% 
  #mutate(n = 1:n()) %>% 
  #filter(n == 1)
  
com_data_pftc <- com_data_full %>% 
  filter(is.na(treatment_only_for_range_x)) %>% 
  select(!treatment_only_for_range_x)

com_data_rangex <- com_data_full %>% 
  filter(!is.na(treatment_only_for_range_x)) 

```
```{r shorten species names}
extr_3 <- function(string) {
  # Split the string into words
  words <- strsplit(string, "_")[[1]]
  # Extract the first three letters from each word
  first_three_letters <- sapply(words, substr, 1, 3)
  # Return the first three letters of each word
  first_three_letters <- paste(first_three_letters, collapse = "")
  return(first_three_letters)
}

com_data_full$spec <- NA

for (i in 1:nrow(com_data_full)) {
  extr <- extr_3(as.data.frame(com_data_full)[i, 7]) 
  com_data_full[i, 10] <- extr
  rm(extr)
}

com_data_full <- com_data_full %>% 
  select(date:treatment_only_for_range_x, spec, cover, fertility_all) 
```


```{r data prep}
#com_data_pftc$plot_code <- paste0("s", com_data_pftc$site_id, "p", com_data_pftc$plot_id, #com_data_pftc$aspect) 
#
#count <- com_data_pftc %>% count(plot_code, species)
#
#  distinct(plot_code)

cov_data_pftc <-  com_data_full %>% 
  distinct() %>% 
  filter(is.na(treatment_only_for_range_x)) %>% 
  select(-date, -treatment_only_for_range_x, -fertility_all, -elevation) %>% 
  distinct() %>% 
  #filter(site_id == 5, aspect == "E", plot_id == 1) |>
  #distinct(species)
  group_by(site_id, aspect, plot_id, spec) %>% 
  mutate(n = 1:n()) %>% 
  filter(n < 2) %>% 
  # distinct(site_id, aspect, plot_id) |>
  # arrange(aspect, site_id, plot_id) |> print(n = Inf)
  pivot_wider(names_from = spec, values_from = cover, values_fill = 0) %>% 
  select(-n)

cov_data_pftc$plot_code <- paste0("s", cov_data_pftc$site_id, "p", cov_data_pftc$plot_id, cov_data_pftc$aspect)

meta_data_pftc <- cov_data_pftc %>% 
  select(plot_code, site_id:plot_id)

cov_data_pftc <- cov_data_pftc %>% 
  select(plot_code, everything())

cov_data_pftc <- cov_data_pftc[, -(2:4)]
```

```{r NMDS}
pftc_dist <- cov_data_pftc %>% 
  select(-plot_code) %>%
  vegdist()

pftc_nmds <- pftc_dist %>% 
  metaMDS() %>% 
  scores(tidy = TRUE) %>% 
  filter(score == "sites") %>% 
  select(NMDS1, NMDS2)
  
spec_nmds <- cov_data_pftc %>%  
  column_to_rownames("plot_code") %>% 
  metaMDS() %>% 
  scores(tidy = TRUE) %>% 
  filter(score == "species") 

meta_nmds <- cbind(meta_data_pftc, pftc_nmds) 

meta_nmds$site_id <- as.factor(meta_nmds$site_id)
  
```

```{r NMDS plot (country), echo = FALSE}
hull_data <- meta_nmds %>% # find convex hulls
  group_by(site_id, aspect) %>% # for each combination of country and habitat
  arrange(NMDS1, NMDS2) %>%
  slice(chull(NMDS1, NMDS2))

ggplot() +
  geom_point(data = meta_nmds, aes(x = NMDS1, y = NMDS2, colour = site_id, shape = aspect), size = 3) + # add the point markers 
  geom_polygon(data = hull_data, aes(x = NMDS1, y = NMDS2, color = site_id, fill = site_id, linetype = aspect), alpha = 0.30) +
  geom_text(data = spec_nmds, aes(x = NMDS1, y = NMDS2, label = label), alpha = 0.5) +  # add the species labels
  #geom_text(data = data_scores, aes(x = NMDS1, y = NMDS2, label = plot), vjust=0) +  # add the site labels
  coord_equal() +
  theme_classic() 

#ggsave("~/Project Green Arctic/3_snow_fences/1_data/1_sf_data_analysis/3_output/3_plots/sf_NMDS_23.svg", height = 4, width = 7)
```


